version: '3'

services:
  autoscout_bot:
    build: ./
    volumes:
      - ./src/:/bot/src
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      #USER postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
